### ISSUE TITLE
Solver and JuMP returns not the same

### ISSUE THREAD

**Issue by jd-lara** [jump-dev/Xpress.jl#212] opened 2024-02-08 00:50 UTC
During some simulation testing with PowerSimulations, this issue appears arbitrarily where the Xpress status doesn't match the the return of `JuMP.primal_status(jump_model)`. The models run in direct mode is this useful to know. 

```
julia> JuMP.solution_summary(ed.internal.container.JuMPmodel)
* Solver : Xpress

* Status
  Result count       : 0
  Termination status : INFEASIBLE
  Message from the solver:
  "6 Global search complete - integer solution found ( XPRS_MIP_OPTIMAL). - no interruption - the solve completed normally"

* Candidate solution (result jump-dev/JuMP.jl#1)
  Primal status      : INFEASIBLE_POINT
  Dual status        : NO_SOLUTION
  Objective bound    : 0.00000e+00

* Work counters
  Solve time (sec)   : 6.38302e-01
```

Another interesting thing is that if I call `optimize!()` again on the model the return is now correct

Julia version 
```
Julia Version 1.10.0
Commit 3120989f39b (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (x86_64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, westmere)
  Threads: 1 on 10 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS =
```

```
(test) pkg> st
Status `~/.julia/dev/PowerSimulations/test/Project.toml`
  [4c88cf16] Aqua v0.8.4
  [336ed68f] CSV v0.10.12
  [9961bab8] Cbc v1.2.0
  [a93c6f00] DataFrames v1.6.1
  [864edb3b] DataStructures v0.18.16
  [60bf3e95] GLPK v1.1.3
⌅ [87dc4568] HiGHS v1.1.2
  [fc1677e0] HydroPowerSimulations v0.8.0
  [2cd47ed4] InfrastructureSystems v1.22.1
⌅ [b6b21f68] Ipopt v1.4.0
  [0f8b85d8] JSON3 v1.14.0
  [4076af6c] JuMP v1.19.0
  [f28f55f0] Memento v1.4.1
⌅ [c36e90e8] PowerModels v0.20.1
  [bed98974] PowerNetworkMatrices v0.10.0
  [e690365d] PowerSimulations v0.27.0 `..`
  [f00506e0] PowerSystemCaseBuilder v1.2.3 `~/.julia/dev/PowerSystemCaseBuilder`
  [bcd98974] PowerSystems v3.2.2
  [295af30f] Revise v3.5.13
  [c946c3f1] SCS v2.0.0
  [e2f1a126] StorageSystemsSimulations v0.9.0
  [98d24dd4] TestSetExtensions v3.0.0
⌅ [9e3dc215] TimeSeries v0.23.2
  [a759f4b9] TimerOutputs v0.5.23
  [ade2ca70] Dates
  [56ddb016] Logging
  [44cfe95a] Pkg v1.10.0
  [9a3f8284] Random
  [9e88b42a] Serialization
  [8dfed614] Test
  [cf7118a7] UUIDs
Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated`
```

**Comment by odow** [comment] 2024-02-08 01:05
Transferred this to Xpress.jl

**Comment by jd-lara** [comment] 2024-02-08 16:31
@odow I have the sense that this issue and #210 are related

**Comment by odow** [comment] 2024-02-09 00:59
Let me take a look.

**Comment by odow** [comment] 2024-02-09 01:00
Can you dump the MPS file of a failing example?

**Comment by odow** [comment] 2024-02-09 01:18
I don't understand this at all. The log makes it look like the problem is actually infeasible: 
```
Problem is infeasible
 *** Search completed ***
Problem is integer infeasible
```

If the problem is actually infeasible. Then the only weird thing is the raw status string?

Can you try with `set_attribute(model, "MOI_POST_SOLVE", false)`

**Comment by odow** [comment] 2024-02-09 01:19
If solving twice fixes it, then that really sounds like an Xpress bug. But it could also be in Xpress.jl... Impossible without an easily reproducible example.

**Comment by jd-lara** [comment] 2024-02-09 03:45
It seems related to the use of the setting `"MAXMEMORYSOFT" => 600000` in combination with problem modification. Once I removed this, the problem hasn't happened again. I added some capabilities in PSI to get infeasible problems written to disk

**Comment by odow** [comment] 2024-02-10 06:12
I talked to @jd-lara. Until proven otherwise, we're marking this as an upstream bug in Xpress. One difficulty is that he's using an old version of Xpress, `FICO Xpress v8.12.3`, so we can't check if it still exists in the latest version.

**Comment by joaquimg** [comment] 2024-02-10 12:06
That is very old indeed.
Looks like some numerical issue.
Xpress has a svf file that is great for debugging. You can write one before and another one right before the problem is first solved and send to fico

**Comment by odow** [comment] 2024-03-11 07:21
I don't know if there is anything left to do here for Xpress.jl.

**Comment by odow** [comment] 2024-03-21 00:42
Okay, so I took another look at this.

I've made a bunch of changes to the solution status handling, but I don't think that's the problem.

I think it might be because of:
```
Coefficient range                    original                 solved        
  Coefficients   [min,max] : [ 3.19e-18,  1.00e+06] / [ 2.01e-05,  1.30e+05]
  RHS and bounds [min,max] : [ 1.39e-17,  1.00e+06] / [ 1.22e-05,  2.57e+09]
  Objective      [min,max] : [ 8.33e-03,  1.00e+06] / [ 1.02e-06,  5.12e+08]
Autoscaling applied Curtis-Reid scaling
```
You have some very small coefficients that are then scaled to `1e-5`, so it seems plausible that during the scaled barrier solve it might detect infeasibility, but then on re-solve (perhaps with simplex, or it doesn't scale) it finds a feasible solution.

You could try setting `"XPRS_SCALING" => 0`.

Regardless, I don't think this is a bug in Xpress.jl.

**Comment by odow** [comment] 2024-03-21 20:09
Closing for now as won't-fix. If anyone runs into something similar with a recent version of Xpress, please comment and we can re-open.

**Closed by odow** 2024-03-21 20:09 UTC
